### ISSUE TITLE
unnecessary vuex

### ISSUE THREAD

**Issue by kovacsgergo8888** [boncsi/secretServerChallenge#12]
Hi!

Itt ez a vuex store, ahogy nézem elég üres, így azt mondanám semmi szükség rá.  

https://github.com/boncsi/secretServerChallenge/blob/53bcea00cb623490093bce2a93f12be39f877fd7/client/secret/src/store/index.js#L1-L11

Ez a vuex store egyébként egy örök kérdés, sok cikk meg fórum van róla, hogy mikor kell egyáltalán bevezetni egy alkalmazásba  
https://vuex.vuejs.org/#when-should-i-use-it  
https://markus.oberlehner.net/blog/should-i-store-this-data-in-vuex/

**Comment by boncsi** [comment]
https://github.com/boncsi/secretServerChallenge/pull/15   @kovacsgergo8888 ezt itt javítottam.

**Comment by kovacsgergo8888** [comment]
Hi @boncsi !  

Igazából így sehol nincs vuex használva, de a package.json-ben benne van, továbbá az main.js-ben hivatkozol az üres fájlra.  
Teljesen ki lehetne pucolni

Üdv,
Gergő

**Comment by boncsi** [comment]
@kovacsgergo8888  kitöröltem itt: https://github.com/boncsi/secretServerChallenge/pull/19 .

**Comment by kovacsgergo8888** [comment]
ez így ok
