### ISSUE TITLE
list item refactor

### ISSUE THREAD

**Issue by kovacsgergo8888** [boncsi/secretServerChallenge#14]
Hali!

https://github.com/boncsi/secretServerChallenge/blob/53bcea00cb623490093bce2a93f12be39f877fd7/client/secret/src/views/Home.vue#L18-L26

Gyakorlásképp: egy listaelemet tök jól ki lehet tenni egy külön komponensbe amin aztán lehet `v-for` -ral végigmenni. Szóval maga a ciklus az maradhatna itt, de hogy hogy néz ki egy sor html-je, az mehetne külön vue fájlba.

_Tovább tipp: a `:key="i"` egy alattomos dolog tud lenni. Ezzel így most semmi gond, de maga a `key=` attribútum a vue-ban egy kiemelt dolog, kvázi egy ID az adott alkalmazásban. Ez itt most elég egyszerű, csak tömb index. Másképp fogalmazva, ha lenne az adott oldalon még egy ciklus, amiben csak a számokat használod, az tud galibát okozni, amikor valamely ciklust újra kell renderelni. Szívtam már vele egy-kétszer :)_

Üdv,
Gergő

**Comment by kovacsgergo8888** [comment]
itt egy leírás a key -ről:  
https://vuejs.org/v2/api/#key

**Comment by boncsi** [comment]
@kovacsgergo8888 ezt itt javítottam https://github.com/boncsi/secretServerChallenge/pull/16 .
