### ISSUE TITLE
Component name casing in templates

### ISSUE THREAD

**Issue by kovacsgergo8888** [boncsi/secretServerChallenge#17]
Hali @boncsi !

https://github.com/boncsi/secretServerChallenge/blob/1e86e3838564c1a4733f22d5e0e98ccdf9f2cab4/client/secret/src/views/Home.vue#L20

A megoldás jó, csak styling probléma lenne. Pont így nem szokás használni:
https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended

Üdv,
Gergő

**Comment by boncsi** [comment]
Hello @kovacsgergo8888   https://github.com/boncsi/secretServerChallenge/pull/18 itt javítottam ezt az elnevezési konvenciót.

**Comment by kovacsgergo8888** [comment]
ez így ok, egyébként nem szükséges a `<template>` tag, a komponensnek is lehet adni v-for direktívát kb így
```vue
<SecretItem v-for="...
```
